-- A10P1

-- CREATE AND POPULATE AIRCRAFT DIMENSION TABLE

CREATE TABLE [dbo].[AIRCRAFTDIM](
	AIRCRAFTKEY INT IDENTITY NOT NULL, --DATAWAREHOUSE KEY
	[AC_NUMBER] [varchar](5) NOT NULL, --TRANSACTION KEY
	[MOD_CODE] [varchar](10) NULL,
	[AC_TTAF] [real] NULL,
	[AC_TTEL] [real] NULL,
	[AC_TTER] [real] NULL
) 

ALTER TABLE AIRCRAFTDIM 
ADD	CONSTRAINT PK_AIRCRAFTDIM PRIMARY KEY (AIRCRAFTKEY)

INSERT INTO AIRCRAFTDIM
SELECT	*
FROM	AIRCRAFT 

--CREATE AND POPULATE PILOT DIMENSION 

CREATE TABLE [dbo].[PILOTDIM](
	PILOTKEY INT IDENTITY NOT NULL, --DATAWAREHOUSE KEY
	[EMP_NUM] [int] NOT NULL, --TRANSACTION KEY
	[EMP_LNAME] [varchar] (25) NULL, 
	[EMP_FNAME] [varchar] (25) NULL,
	[PIL_LICENSE] [varchar](25) NULL,
	[PIL_RATINGS] [varchar](25) NULL,
	[PIL_MED_TYPE] [varchar](1) NULL,
	[PIL_MED_DATE] [datetime] NULL,
	[PIL_PT135_DATE] [datetime] NULL
) 
ALTER TABLE PILOTDIM 
ADD	CONSTRAINT PK_PILOTDIM PRIMARY KEY (PILOTKEY)

INSERT INTO PILOTDIM
SELECT	E.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, P.PIL_LICENSE, P.PIL_RATINGS, P.PIL_MED_TYPE, P.PIL_MED_DATE, P.PIL_PT135_DATE
FROM	PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM 
 

--CREATE AND POPULATE TIME DIMENSION 

CREATE TABLE [dbo].[TIMEDIM](
	TIMEKEY INT IDENTITY NOT NULL, --DATAWAREHOUSE KEY
	[CHAR_DATE] [datetime] NOT NULL, --TRANSACTION KEY 
	YEAR INT NULL,
	MONTH INT NULL,
) 
ALTER TABLE TIMEDIM 
ADD CONSTRAINT PK_TIMEDIM PRIMARY KEY (TIMEKEY)
-- SET CONSTRAINTS 

INSERT INTO TIMEDIM
SELECT	DISTINCT CHAR_DATE, YEAR(char_date), MONTH(char_date) 
FROM	CHARTER  

SELECT	*
FROM	TIMEDIM 

-- CREATE FACT TABLE 

CREATE TABLE [dbo].[FACT](
	TIMEKEY	INT NOT NULL, 
	PILOTKEY INT NOT NULL, 
	AIRCRAFTKEY INT NOT NULL, 
	CHAR_DISTANCE REAL NULL, 
	CHAR_FUEL_GALLONS REAL NULL, 
	MOD_CHG_MILE REAL NULL
)
ALTER TABLE FACT 
ADD CONSTRAINT PK_FACT PRIMARY KEY (TIMEKEY, PILOTKEY, AIRCRAFTKEY),
	CONSTRAINT FK_TIMEDIM FOREIGN KEY (TIMEKEY) REFERENCES TIMEDIM,
	CONSTRAINT FK_PILOTDIM FOREIGN KEY (PILOTKEY) REFERENCES PILOTDIM, 
	CONSTRAINT FK_AIRCRAFTDIM FOREIGN KEY (AIRCRAFTKEY) REFERENCES AIRCRAFTDIM 


-- CREATE STAGING TABLE 

CREATE TABLE [dbo].[STAGING](
	TIMEKEY	INT, 
	PILOTKEY INT, 
	AIRCRAFTKEY INT, 
	[AC_NUMBER] [varchar](5),
	[EMP_NUM] [int],
	[CHAR_DATE] [datetime],
	CHAR_DISTANCE REAL, 
	CHAR_FUEL_GALLONS REAL, 
	MOD_CHG_MILE REAL
)

--POPULATE THE STAGING TABLE 

-- FIRST, POPULATE THE TKs AND THE FACTS 
INSERT INTO STAGING (AC_NUMBER, EMP_NUM, CHAR_DATE, CHAR_DISTANCE, CHAR_FUEL_GALLONS, MOD_CHG_MILE)
SELECT	A.AC_NUMBER, P.EMP_NUM, C.CHAR_DATE, C.CHAR_DISTANCE, C.CHAR_FUEL_GALLONS, 
		M.MOD_CHG_MILE 
FROM	AIRCRAFT A INNER JOIN CHARTER C ON A.AC_NUMBER = C.AC_NUMBER
		INNER JOIN CREW CR ON C.CHAR_TRIP = CR.CHAR_TRIP 
		INNER JOIN EMPLOYEE E ON CR.EMP_NUM = E.EMP_NUM 
		INNER JOIN PILOT P ON E.EMP_NUM = P.EMP_NUM 
		INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE  

-- SECOND, ASSIGN THE DATAWAREHOUSE KEYS 

UPDATE	STAGING 
SET		TIMEKEY = T.TIMEKEY 
FROM	STAGING S INNER JOIN TIMEDIM T ON S.CHAR_DATE = T.CHAR_DATE 

UPDATE	STAGING 
SET		PILOTKEY = P.PILOTKEY 
FROM	STAGING S INNER JOIN PILOTDIM P ON S.EMP_NUM = P.EMP_NUM 

UPDATE	STAGING 
SET		AIRCRAFTKEY = A.AIRCRAFTKEY 
FROM	STAGING S INNER JOIN AIRCRAFTDIM A ON S.AC_NUMBER = A.AC_NUMBER

-- CHECK STAGING TABLE 
SELECT	*
FROM	STAGING  

-- POPULATE FACT TABLE 
INSERT INTO FACT 
SELECT	TIMEKEY, PILOTKEY, AIRCRAFTKEY, CHAR_DISTANCE, CHAR_FUEL_GALLONS, MOD_CHG_MILE 
FROM	STAGING 

--CHECK FACT TABLE 
SELECT	*
FROM	FACT 





