--A10P3

ALTER PROCEDURE A10P3 

AS 
BEGIN 
BEGIN 

-- STEP 1: DROP ALL CONSTRAINTS FOR THE FACT TABLE 

ALTER TABLE FACT
DROP CONSTRAINT PK_FACT 

ALTER TABLE FACT 
DROP CONSTRAINT FK_TIMEDIM 

ALTER TABLE FACT 
DROP CONSTRAINT FK_PILOTDIM

ALTER TABLE FACT 
DROP CONSTRAINT FK_AIRCRAFTDIM 

END 

-- STEP 2: TRUNCATE ALL TABLES (FACT AND DIMENSION TABLES) 
BEGIN 

TRUNCATE TABLE FACT
TRUNCATE TABLE AIRCRAFTDIM
TRUNCATE TABLE PILOTDIM 
TRUNCATE TABLE TIMEDIM 

END 

-- DO I NEED TO RESET THE FACT TABLE CONSTAINTS?
BEGIN 

ALTER TABLE FACT 
ADD CONSTRAINT PK_FACT PRIMARY KEY (TIMEKEY, PILOTKEY, AIRCRAFTKEY),
	CONSTRAINT FK_TIMEDIM FOREIGN KEY (TIMEKEY) REFERENCES TIMEDIM,
	CONSTRAINT FK_PILOTDIM FOREIGN KEY (PILOTKEY) REFERENCES PILOTDIM, 
	CONSTRAINT FK_AIRCRAFTDIM FOREIGN KEY (AIRCRAFTKEY) REFERENCES AIRCRAFTDIM 

END 

-- STEP 3 & 4: POPULATE DIMENSION TABLES FROM TRANSACTION DATA 

BEGIN 

INSERT INTO AIRCRAFTDIM
SELECT	*
FROM	AIRCRAFT 

INSERT INTO PILOTDIM
SELECT	E.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, P.PIL_LICENSE, P.PIL_RATINGS, P.PIL_MED_TYPE, P.PIL_MED_DATE, P.PIL_PT135_DATE
FROM	PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM 

INSERT INTO TIMEDIM
SELECT	DISTINCT CHAR_DATE, YEAR(char_date), MONTH(char_date) 
FROM	CHARTER   

INSERT INTO FACT 
SELECT	TIMEKEY, PILOTKEY, AIRCRAFTKEY, CHAR_DISTANCE, CHAR_FUEL_GALLONS, MOD_CHG_MILE 
FROM	STAGING 

END 
END 